In [1]:
import pandas as pd
import datetime
import numpy as np
from tqdm import tqdm_notebook
from datetime import datetime,timedelta
import os
from timeit import default_timer as timer
from scipy import stats
from sklearn import linear_model
import matplotlib.pyplot as plt

path='/Users/hudsonyeo/Desktop/Python/leo/data/day/TA'
os.chdir('/Users/hudsonyeo/Desktop/Python/leo/data/day/TA')
file_list=os.listdir(path)
file_list.sort()

In [2]:
file_list

['.DS_Store',
 '2019.01.02.csv',
 '2019.01.03.csv',
 '2019.01.04.csv',
 '2019.01.07.csv',
 '2019.01.08.csv',
 '2019.01.09.csv',
 '2019.01.10.csv',
 '2019.01.11.csv',
 '2019.01.14.csv',
 '2019.01.15.csv',
 '2019.01.16.csv',
 '2019.01.17.csv',
 '2019.01.18.csv',
 '2019.01.21.csv',
 '2019.01.22.csv',
 '2019.01.23.csv',
 '2019.01.24.csv',
 '2019.01.25.csv',
 '2019.01.28.csv',
 '2019.01.29.csv',
 '2019.01.30.csv',
 '2019.01.31.csv',
 '2019.02.01.csv',
 '2019.02.11.csv',
 '2019.02.12.csv',
 '2019.02.13.csv',
 '2019.02.14.csv',
 '2019.02.15.csv',
 '2019.02.18.csv',
 '2019.02.19.csv',
 '2019.02.20.csv',
 '2019.02.21.csv',
 '2019.02.22.csv',
 '2019.02.25.csv',
 '2019.02.26.csv',
 '2019.02.27.csv',
 '2019.02.28.csv',
 '2019.03.01.csv',
 '2019.03.04.csv',
 '2019.03.05.csv',
 '2019.03.06.csv',
 '2019.03.07.csv',
 '2019.03.08.csv',
 '2019.03.11.csv',
 '2019.03.12.csv',
 '2019.03.13.csv',
 '2019.03.14.csv',
 '2019.03.15.csv',
 '2019.03.18.csv',
 '2019.03.19.csv',
 '2019.03.20.csv',
 '2019.03.21.csv'

In [3]:
class categorise():
    def __init__(self):
        self.threshold=[]
        self.percentiles=[25,50,75]
        
    def fit(self,array):
        positive=array[array>0]
        negative=array[array<0]
        self.threshold.append(np.percentile(negative,self.percentiles))   
        self.threshold.append(np.percentile(positive,self.percentiles))
     
    def return_quartile(self,array):
        temp=[]
        for i in array:
            if i>=0:
                if i<self.threshold[1][0]:
                    temp.append(5)
                elif i<self.threshold[1][1]:
                    temp.append(6)
                elif i<self.threshold[1][2]:
                    temp.append(7)
                else:
                    temp.append(8)
            if i<0:
                if i>self.threshold[0][2]:
                    temp.append(4)
                elif i>self.threshold[0][1]:
                    temp.append(3)
                elif i>self.threshold[0][0]:
                    temp.append(2)
                else:
                    temp.append(1)
        return np.asarray(temp)
    
class categorise_simple():
    def __init__(self):
        self.threshold=[]
        self.percentiles=[25,50,75]
        
    def fit(self,array):
        self.threshold.append(np.percentile(array,self.percentiles))
     
    def return_quartile(self,array):
        temp=[]
        for i in array:
                if i<self.threshold[0][0]:
                    temp.append(1)
                elif i<self.threshold[0][1]:
                    temp.append(2)
                elif i<self.threshold[0][2]:
                    temp.append(3)
                else:
                    temp.append(4)
        return np.asarray(temp)    
    
class categorise_10():
    def __init__(self):
        self.threshold=[]
        self.percentiles=[10,20,30,40,50,60,70,80,90]
        
    def fit(self,array):
        positive=array[array>0]
        negative=array[array<0]
        self.threshold.append(np.percentile(negative,self.percentiles))   
        self.threshold.append(np.percentile(positive,self.percentiles))
     
    def return_quartile(self,array):
        temp=[]
        for i in array:
            if i>=0:
                if i<self.threshold[1][0]:
                    temp.append(11)
                elif i<self.threshold[1][1]:
                    temp.append(12)
                elif i<self.threshold[1][2]:
                    temp.append(13)
                elif i<self.threshold[1][3]:
                    temp.append(14)
                elif i<self.threshold[1][4]:
                    temp.append(15)
                elif i<self.threshold[1][5]:
                    temp.append(16)
                elif i<self.threshold[1][6]:
                    temp.append(17)
                elif i<self.threshold[1][7]:
                    temp.append(18)
                elif i<self.threshold[1][8]:
                    temp.append(19)                    
                else:
                    temp.append(20)
            if i<0:
                if i<self.threshold[0][0]:
                    temp.append(1)
                elif i<self.threshold[0][1]:
                    temp.append(2)
                elif i<self.threshold[0][2]:
                    temp.append(3)
                elif i<self.threshold[0][3]:
                    temp.append(4)
                elif i<self.threshold[0][4]:
                    temp.append(5)
                elif i<self.threshold[0][5]:
                    temp.append(6)
                elif i<self.threshold[0][6]:
                    temp.append(7)
                elif i<self.threshold[0][7]:
                    temp.append(8)
                elif i<self.threshold[0][8]:
                    temp.append(9)                    
                else:
                    temp.append(10)
        return np.asarray(temp)    
    
class categorise_x(): #flexible number of categories
    
    def __init__(self,x):
        self.threshold=[]
        self.percentiles=[]
        self.num=x
        for i in range(1,x):
            self.percentiles.append(i*100/x)        
            
    def fit(self,array):
        
        positive=array[array>0]
        negative=array[array<=0]
        self.threshold.append(np.percentile(negative,self.percentiles))   
        self.threshold.append(np.percentile(positive,self.percentiles))
        
    def return_quartile(self,array):
        temp=[]
        for num in array:
            if num<0:
                counter=0
                for i in self.threshold[0]:
                    if num>=i:
                        counter+=1
                    else:
                        break
                temp.append(counter+1)
            else:
                counter=0
                for i in self.threshold[1]:
                    if num>=i:
                        counter+=1
                    else:
                        break
                temp.append(counter+self.num+1)
        return np.asarray(temp)
    
class cross():
    def __init__(self):
        self.time_last_cross=0
        self.current_sign=True
        self.last_time=datetime(1900, 1, 1, 8, 59)
    def get_time(self,time,price):
        if (time-self.last_time)>timedelta(minutes=1):
            self.last_time=time
            self.time_last_cross=time
            return 0
        self.last_time=time
        if (price>0) and self.current_sign : #if price positive and current trend is also positive
            return (time-self.time_last_cross).total_seconds()
        elif (price<0) and (not self.current_sign): #if price negative and current trend is negative
            return (time-self.time_last_cross).total_seconds()
        else: #if price positive, trend negative or price negative, trend positive
            self.time_last_cross=time
            self.current_sign=(price>0)
            return 0

In [60]:
def calc_smart_price(dataset):
    data=dataset.copy()
    
    #to combat the limit up event, where price is set to 0. 
    rows=(data.loc[:,'BidPrice1']==0) #count rows of bid price equal 0
    if (np.any(rows)): #if there is such a row
        data.at[rows,'BidPrice1']=data.loc[rows,'AskPrice1'] #for that row, assign ask price to it
    rows=(data.loc[:,'AskPrice1']==0) #do the same for ask price
    if (np.any(rows)):
        data.at[rows,'AskPrice1']=data.loc[rows,'BidPrice1'] 
        
    data['smart_price']=data.loc[:,'BidPrice1']*data.loc[:,'AskVol1']+data.loc[:,'AskPrice1']*data.loc[:,'BidVol1']
    data.at[:,'smart_price']=data.loc[:,'smart_price']/(data.loc[:,['BidVol1','AskVol1']].sum(axis=1))  
    return data

def calc_present_vol(dataset):
    data=dataset.copy()
    data['current_vol']=data.loc[:,'Volume'].diff().fillna(0)/2
    return data

def calc_future_price(dataset,time_ahead=30,time_index=44, price_col=-2):
    data=dataset.copy()
    future_price=[]
    length=len(data)
    for i in range(len(data)):
        current_time=data[i,time_index]+timedelta(seconds=time_ahead)
        
        j=0 #could alternatively use 30 x 3 then search forward and backward
        
        #search forwards
        while((i+j)<length and current_time>data[(i+j),time_index]):
            j+=1
        if (i+j)<length:
            #if index is in the dataframe
            future_price.append(data[(i+j),price_col]) 
        else:
            #price ahead does not exist
            future_price.append(np.nan) 
    future_price=np.asarray(future_price)
    future_price=np.expand_dims(future_price,axis=1)
    return np.concatenate((data,future_price),axis=1)

def calc_edge(dataset,future_col,current_col):
    data=dataset.copy()
    temp=data[:,future_col]-data[:,current_col]
    temp=np.expand_dims(temp,axis=1)
    return np.concatenate((data,temp),axis=1)

def set_index(dataset,time_index=44):
    data=dataset.copy()
    index=data[:,time_index]
    new_index=[]
    for j in range(len(index)):
        i=str(index[j]*1000)
        if len(i)==11:
            i='0'+i
        i=i[:-10]+':'+i[-10:]
        i=i[:-8]+':'+i[-8:]
        i=i[:-6]+':'+i[-6:]
        new_index.append(datetime.strptime(i,"%H:%M:%S:%f"))
    data[:,time_index]=new_index
    return data

def calc_sma_fast(dataset,price_col,duration=1,time_index=44): #faster way to calculate SMA, 0.05 seconds for 5000 rows
    data=dataset.copy()
    sma_values=[] 
    smart_sum=np.cumsum(data[:,price_col]) #smart price column is -4
    for i in range(len(data)):
        
        #finding ending point
        last_time=data[i,time_index]-timedelta(minutes=duration)
        
        #finding start point
        j=220*duration#4x60=240
        
        if i-j>0:
            if data[i-j,time_index]>last_time: 
                
                #if starting point time is greater than ending point time
                #search backward
                while(i-j>0 and data[i-j,time_index]>last_time):
                    j+=1
                    
                #activate next line in order to debug and troubleshoot
                #print('backward',i,j,data[i,time_index],data[i-j,time_index],last_time)
                
                sma=(smart_sum[i]-smart_sum[i-j-1])/(j+1)
                sma_values.append(sma)                
                
            else: 
                
                #search forward
                while(data[i-j,time_index]<last_time):
                    j-=1
                    
                #activate next line in order to debug and troubleshoot
                #print('forward',i,j,data[i,time_index],data[i-j,time_index],last_time)
                
                if j!=0:
                    sma=(smart_sum[i]-smart_sum[i-j-1])/(j+1)
                    sma_values.append(sma)   
                    
                else:
                    sma_values.append(data[i,price_col])
                    
        else: #starting point is at 0
            
            sma=smart_sum[i]/(i+1)
            sma_values.append(sma)                       

    sma_values=np.asarray(sma_values)
    sma_values=data[:,price_col]-sma_values
    sma_values=np.expand_dims(sma_values,axis=1)
    return np.concatenate((data,sma_values),axis=1)  

def calc_volatility_slow(dataset,price_col,duration=15,time_index=44): 
    data=dataset.copy()
    diff=np.diff(dataset[:,price_col])
    diff=np.insert(diff,0,0)
    
    volatility_values=[]
    for i in range(len(data)):
            
        #finding ending point
        last_time=data[i,time_index]-timedelta(minutes=duration)
        
        #finding start point
        j=220*duration#4x60=240
        
        if i-j>0:
            if data[i-j,time_index]>last_time: 
                #if starting point time is greater than ending point time
                #search backward
                while(i-j>0 and data[i-j,time_index]>last_time):
                    j+=1
                vol=np.std(diff[i-j:i])
                volatility_values.append(vol)                     
            else: 
                #search forward
                while(data[i-j,time_index]<last_time):
                    j-=1
                if j!=0:
                    vol=np.std(diff[i-j:i])
                    volatility_values.append(vol) 
                else:
                    volatility_values.append(0)
        else: #starting point is at 0
            if i==0:
                volatility_values.append(0)
                continue
            vol=np.std(diff[:i])
            volatility_values.append(vol)   
            
    volatility_values=np.asarray(volatility_values)
    volatility_values=np.expand_dims(volatility_values,axis=1)
    return np.concatenate((data,volatility_values),axis=1)

def calc_past_vol(dataset,vol_col,duration=1,time_index=44): #
    data=dataset.copy()
    vol_values=[] 
    vol_sum=np.cumsum(data[:,vol_col])
    for i in range(len(data)):
        last_time=data[i,time_index]-timedelta(minutes=duration)
        j=220*duration#4x60=240
        while(i-j>0 and data[i-j,time_index]>last_time):
            j+=1
        if (i-j>=0):
            vol=(vol_sum[i]-vol_sum[i-j])
            vol_values.append(vol)
        else:
            vol=vol_sum[i]
            vol_values.append(vol)
    vol_values=np.asarray(vol_values)
    vol_values=np.expand_dims(vol_values,axis=1)
    return np.concatenate((data,vol_values),axis=1) 

def last_cross(dataset,price_col,time_index=44):
    data=dataset.copy()
    last_cross=cross()
    timings=[]
    for i in range(len(data)):
        timings.append(last_cross.get_time(data[i,time_index],data[i,price_col]))
    timings=np.asarray(timings)
    timings=np.expand_dims(timings,axis=1)
    return np.concatenate((data,timings),axis=1)

def get_case(array):
    current=1
    previous=0
    temp=[]
    for i in array:
        if i==current:
            if i>previous:
                temp.append(1)
            else:
                temp.append(0)
        elif i>current:
            previous=current
            current=i
            temp.append(1)
        else:
            previous=current
            current=i
            temp.append(0)
    return np.asarray(temp)


def binaryToDecimal(binary): 
      
    binary1 = binary 
    decimal, i, n = 0, 0, 0
    while(binary != 0): 
        dec = binary % 10
        decimal = decimal + dec * pow(2, i) 
        binary = binary//10
        i += 1
    return(decimal) 
    
def get_case_n(array,n=2):
    temp=[]
    if n==1:
        return("error")
    previous=np.zeros(n)
    for i in array:
        final=''
        if i==int(previous[-1]):
            before=10
            for j in previous:
                if j>before:
                    final+='1'
                else:
                    final+='0'
                before=int(j)
        else:
            before=10
            for j in previous:
                if j>before:
                    final+='1'
                else:
                    final+='0'
                before=int(j)
            final=final[1:]
            if i>before:
                final+='1'
            else:
                final+='0'
        
            previous=np.delete(previous,0)
            previous=np.insert(previous,(n-1),i)
#        temp.append(final)            
        temp.append(binaryToDecimal(int(final)))
    return np.asarray(temp)    

def process(dataset,sma_duration=1,vol_duration=1,time_index=44):
    data=dataset[:]
    data=calc_smart_price(data).values #new
    data=set_index(data,time_index=time_index) #no change
    data=calc_future_price(data,time_index=time_index,price_col=-1) #new
    data=calc_edge(data,future_col=-1,current_col=-2) #new
    data=calc_sma_fast(data,duration=sma_duration,time_index=time_index,price_col=-3) #new
    return data

In [65]:
#demonstration of get_case_n function
get_case_n(np.array([12,3,5,4,2,1,1,2,3,5,12]),2)

array([2, 3, 2, 3, 1, 1, 1, 2, 4, 4, 4])

In [ ]:
#processing raw data to get technicals
df_list=[]
name_list=[]
ma_time=5
path='/Users/hudsonyeo/Desktop/Python/leo/data/day/TA/'
for file in file_list: #read all files and add them to file_list
    if file[-3:]=='csv': #check if file is a CSV
        name_list.append(file)
        df_list.append(process(pd.read_csv(path+file),sma_duration=ma_time))
        print(file,'read')

2019.01.02.csv read
2019.01.03.csv read
2019.01.04.csv read
2019.01.07.csv read
2019.01.08.csv read
2019.01.09.csv read
2019.01.10.csv read
2019.01.11.csv read
2019.01.14.csv read
2019.01.15.csv read
2019.01.16.csv read
2019.01.17.csv read
2019.01.18.csv read
2019.01.21.csv read
2019.01.22.csv read
2019.01.23.csv read
2019.01.24.csv read
2019.01.25.csv read
2019.01.28.csv read
2019.01.29.csv read
2019.01.30.csv read
2019.01.31.csv read
2019.02.01.csv read
2019.02.11.csv read
2019.02.12.csv read
2019.02.13.csv read
2019.02.14.csv read
2019.02.15.csv read
2019.02.18.csv read
2019.02.19.csv read
2019.02.20.csv read
2019.02.21.csv read
2019.02.22.csv read
2019.02.25.csv read
2019.02.26.csv read
2019.02.27.csv read
2019.02.28.csv read
2019.03.01.csv read
2019.03.04.csv read
2019.03.05.csv read
2019.03.06.csv read
2019.03.07.csv read
2019.03.08.csv read
2019.03.11.csv read
2019.03.12.csv read
2019.03.13.csv read
2019.03.14.csv read
2019.03.15.csv read
2019.03.18.csv read
2019.03.19.csv read


In [ ]:
#calculating results
df_path='/Users/hudsonyeo/Desktop/Python/leo/data/day/TA/results/'

n=2

#create a list to hold all the data
data_list=[]
#creating a list for each category
for i in range(20):
    data_list.append([])
    #creating a list for each quartile
    for _ in range((2**n)):
        data_list[i].append([])
        
for i in range(len(df_list)): #for each 20 day rolling window
    if i<19: #skip first 19 days
        continue
    print(name_list[i])

    #get -19 day
    sma=df_list[i-19][:,-1].copy() #column for SMA
    
    #get -18 to 0 day (19 days in total)
    for k in range((i-18),i+1): #get 20 day moving averages
        sma=np.concatenate((sma,df_list[k][:,-1].copy()))
        
    cat_sma=categorise_10()
    cat_sma.fit(sma) #calculate quartile thresholds for past 20 days

    #get x,y for regression
    x_today=df_list[i][:,-1].copy().astype(float) #column for SMA     
    y_today=df_list[i][:,-2].copy().astype(float) #column for edge
    
    #removing all NA
    isnum=(~np.isnan(x_today)) & (~np.isnan(y_today))
    x_today=x_today[isnum]
    y_today=y_today[isnum]    
    #get categories of today's sma  
    cat_x_today=cat_sma.return_quartile(x_today)
    change=get_case_n(cat_x_today,n)
    
    #for each category
    for cat in range(1,21):
    
        #today's sma filter
        sma_filter_today=(cat_x_today==cat)

        #for each case
        for case in range(2**n):
                
            filtered= sma_filter_today & (change==case) #filtering by SMA and case
            new_y=y_today[filtered].copy()

            if (len(new_y)!=0):
                #add today's data into the list by category and case
                data_list[(cat-1)][case].append(new_y) 
final_df=pd.DataFrame()                 
for cat in range(20):
    for case in range(2**n):
        reg_result={}
        if len(data_list[cat][case])==0:
            reg_result['category']=cat+1
            reg_result['case']=case+1
            reg_result['mean']=np.nan
            reg_result['std']=np.nan
            reg_result['num obs']=0
            final_df=final_df.append(reg_result,ignore_index=True)             
            continue
            
        #getting all the data needed to calculate mean and std
        all_data=data_list[cat][case][0].copy()
        for i in range(1,(len(data_list[cat][case]))):
            all_data=np.concatenate((all_data,data_list[cat][case][i].copy()))

        #adding results to output
        reg_result['category']=cat+1
        reg_result['case']=case+1
        reg_result['mean']=np.mean(all_data)
        reg_result['std']=np.std(all_data)
        reg_result['num obs']=len(all_data)
        final_df=final_df.append(reg_result,ignore_index=True) 
             
temp=df_path+'result_10split_'+str(2**n)+'cases_'+str(ma_time)+'min_sma_weightedmean.csv'
final_df.to_csv(temp)
print('done',temp)            

In [56]:
#interpretation of case results
for x in ['0','1']:
    for y in ['0','1']:
        print(x+y,binaryToDecimal(int(x+y))+1)
# 0 indicates decrease, 1 indicates increase

00 1
01 2
10 3
11 4


In [66]:
for time in [1,3,5,10]:
    try:
        data=pd.read_csv('/Users/hudsonyeo/Desktop/Python/leo/data/day/TA/results/result_10split_4cases_'+str(time)+'min_sma_weightedmean.csv')
    except:
        continue
    length=len(data)
    print(time,'minute MA')
    print('mean')
    print(np.reshape(data.loc[:,'mean'].values,(20,4)))
    print('std')
    print(np.reshape(data.loc[:,'std'].values,(20,4)))
    print('num obs')
    print(np.reshape(data.loc[:,'num obs'].values,(20,4)))

1 minute MA
mean
[[-0.10123765         nan -0.22224872         nan]
 [-0.21845741  0.08265356 -0.34498651         nan]
 [-0.27631761 -0.03164807 -0.33938919  0.03531408]
 [-0.20701956 -0.02084277 -0.16618014  0.13997762]
 [-0.30108895  0.01080844 -0.32577298  0.18572127]
 [-0.29864848 -0.0557268  -0.0973267   0.16684549]
 [-0.26975039 -0.04590963 -0.13803736  0.16018784]
 [-0.36018879 -0.03437015 -0.19268968  0.17345851]
 [-0.28373105 -0.02128981 -0.09507237  0.20451147]
 [-0.32085268  0.05248896 -0.14408516  0.19682824]
 [-0.2294909   0.16387443 -0.18530666  0.26140565]
 [-0.22123366  0.09640732 -0.08697581  0.26075438]
 [-0.21236527  0.24242495 -0.02913809  0.30804359]
 [-0.19267353  0.21498476 -0.05540559  0.27182402]
 [-0.14719781  0.16353381 -0.00784121  0.27025168]
 [-0.09709343  0.40686389  0.04342834  0.25684396]
 [-0.12037499  0.34109759  0.05604844  0.28712703]
 [-0.10929727  0.31791287  0.04905949  0.23291513]
 [        nan  0.4190952  -0.0443465   0.33643283]
 [        nan 

In [68]:
test=pd.read_csv('/Users/hudsonyeo/Desktop/Python/leo/data/day/TA/results/result_10split_4cases_3min_sma_weightedmean.csv')