In [1]:
import pandas as pd
import datetime
import numpy as np
from tqdm import tqdm_notebook
from datetime import datetime,timedelta
import os
from timeit import default_timer as timer
from scipy import stats
import matplotlib.pyplot as plt
dir_path='/Users/hudsonyeo/Desktop/Python/leo/data/day'
os.chdir('/Users/hudsonyeo/Desktop/Python/leo/data/day')
import time
def process_dir(dir_list):
    x=[]
    for dir_ in dir_list:
        if dir_!='.DS_Store':
            x.append(dir_path+'/'+dir_+'/')
    return x
standard_columns=pd.read_csv('/Users/hudsonyeo/Desktop/Python/leo/data/day/TA/2019.01.02.csv').columns

In [2]:
dir_list_names=os.listdir(dir_path)
dir_list_names.sort()
print(dir_list_names)
dir_list=process_dir(dir_list_names)
dir_list

['.DS_Store', 'RM', 'SR', 'TA', 'c', 'fu', 'm', 'ni', 'zn']


['/Users/hudsonyeo/Desktop/Python/leo/data/day/RM/',
 '/Users/hudsonyeo/Desktop/Python/leo/data/day/SR/',
 '/Users/hudsonyeo/Desktop/Python/leo/data/day/TA/',
 '/Users/hudsonyeo/Desktop/Python/leo/data/day/c/',
 '/Users/hudsonyeo/Desktop/Python/leo/data/day/fu/',
 '/Users/hudsonyeo/Desktop/Python/leo/data/day/m/',
 '/Users/hudsonyeo/Desktop/Python/leo/data/day/ni/',
 '/Users/hudsonyeo/Desktop/Python/leo/data/day/zn/']

In [53]:
file_list=get_file_list('/Users/hudsonyeo/Desktop/Python/leo/data/day/fu/')
file_list.sort()
file_list[1]
pd.read_csv('/Users/hudsonyeo/Desktop/Python/leo/data/day/fu/'+file_list[1])

date   ReceiveTime Market  Symbol       Time  OpenPrice  \
0      2019-01-02  1.546391e+15      A  fu1905   85900500       2400   
1      2019-01-02  1.546391e+15      A  fu1905   90000500       2400   
2      2019-01-02  1.546391e+15      A  fu1905   90001000       2400   
3      2019-01-02  1.546391e+15      A  fu1905   90001500       2400   
4      2019-01-02  1.546391e+15      A  fu1905   90002000       2400   
5      2019-01-02  1.546391e+15      A  fu1905   90002500       2400   
6      2019-01-02  1.546391e+15      A  fu1905   90003000       2400   
7      2019-01-02  1.546391e+15      A  fu1905   90003500       2400   
8      2019-01-02  1.546391e+15      A  fu1905   90004000       2400   
9      2019-01-02  1.546391e+15      A  fu1905   90004500       2400   
10     2019-01-02  1.546391e+15      A  fu1905   90005000       2400   
11     2019-01-02  1.546391e+15      A  fu1905   90005500       2400   
12     2019-01-02  1.546391e+15      A  fu1905   90006000       2400   
13     2019-01-02  1.546391e+15      A  fu1905   90006500       2400   
14     2019-01-02  1.546391e+15      A  fu1905   90007000       2400   
15     2019-01-02  1.546391e+15      A  fu1905   90007500       2400   
16     2019-01-02  1.546391e+15      A  fu1905   90008000       2400   
17     2019-01-02  1.546391e+15      A  fu1905   90008500       2400   
18     2019-01-02  1.546391e+15      A  fu1905   90009000       2400   
19     2019-01-02  1.546391e+15      A  fu1905   90009500       2400   
20     2019-01-02  1.546391e+15      A  fu1905   90010000       2400   
21     2019-01-02  1.546391e+15      A  fu1905   90010500       2400   
22     2019-01-02  1.546391e+15      A  fu1905   90011000       2400   
23     2019-01-02  1.546391e+15      A  fu1905   90011500       2400   
24     2019-01-02  1.546391e+15      A  fu1905   90012000       2400   
25     2019-01-02  1.546391e+15      A  fu1905   90012500       2400   
26     2019-01-02  1.546391e+15      A  fu1905   90013000       2400   
27     2019-01-02  1.546391e+15      A  fu1905   90013500       2400   
28     2019-01-02  1.546391e+15      A  fu1905   90014000       2400   
29     2019-01-02  1.546391e+15      A  fu1905   90014500       2400   
...           ...           ...    ...     ...        ...        ...   
26552  2019-01-02  1.546412e+15      A  fu1905  145946000       2400   
26553  2019-01-02  1.546412e+15      A  fu1905  145946500       2400   
26554  2019-01-02  1.546412e+15      A  fu1905  145947000       2400   
26555  2019-01-02  1.546412e+15      A  fu1905  145947500       2400   
26556  2019-01-02  1.546412e+15      A  fu1905  145948000       2400   
26557  2019-01-02  1.546412e+15      A  fu1905  145948500       2400   
26558  2019-01-02  1.546412e+15      A  fu1905  145949000       2400   
26559  2019-01-02  1.546412e+15      A  fu1905  145949500       2400   
26560  2019-01-02  1.546412e+15      A  fu1905  145950000       2400   
26561  2019-01-02  1.546412e+15      A  fu1905  145950500       2400   
26562  2019-01-02  1.546412e+15      A  fu1905  145951000       2400   
26563  2019-01-02  1.546412e+15      A  fu1905  145951500       2400   
26564  2019-01-02  1.546412e+15      A  fu1905  145952000       2400   
26565  2019-01-02  1.546412e+15      A  fu1905  145952500       2400   
26566  2019-01-02  1.546412e+15      A  fu1905  145953000       2400   
26567  2019-01-02  1.546412e+15      A  fu1905  145953500       2400   
26568  2019-01-02  1.546412e+15      A  fu1905  145954000       2400   
26569  2019-01-02  1.546412e+15      A  fu1905  145954500       2400   
26570  2019-01-02  1.546412e+15      A  fu1905  145955000       2400   
26571  2019-01-02  1.546412e+15      A  fu1905  145955500       2400   
26572  2019-01-02  1.546412e+15      A  fu1905  145956000       2400   
26573  2019-01-02  1.546412e+15      A  fu1905  145956500       2400   
26574  2019-01-02  1.546412e+15      A  fu1905  145957000       2400   
26575  2019-01-02  1.546412e+15      A  fu1905  14595

In [44]:
def get_file_list(dir_path):
    return os.listdir(dir_path)

class categorise():
    def __init__(self):
        self.threshold=[]
        self.percentiles=[25,50,75]
        
    def fit(self,array):
        positive=array[array>0]
        negative=array[array<0]
        self.threshold.append(np.percentile(negative,self.percentiles))   
        self.threshold.append(np.percentile(positive,self.percentiles))
     
    def return_quartile(self,array):
        temp=[]
        for i in array:
            if i>=0:
                if i<self.threshold[1][0]:
                    temp.append(5)
                elif i<self.threshold[1][1]:
                    temp.append(6)
                elif i<self.threshold[1][2]:
                    temp.append(7)
                else:
                    temp.append(8)
            if i<0:
                if i>self.threshold[0][2]:
                    temp.append(4)
                elif i>self.threshold[0][1]:
                    temp.append(3)
                elif i>self.threshold[0][0]:
                    temp.append(2)
                else:
                    temp.append(1)
        return np.asarray(temp)
    
class categorise_simple():
    def __init__(self):
        self.threshold=[]
        self.percentiles=[25,50,75]
        
    def fit(self,array):
        self.threshold.append(np.percentile(array,self.percentiles))
     
    def return_quartile(self,array):
        temp=[]
        for i in array:
                if i<self.threshold[0][0]:
                    temp.append(1)
                elif i<self.threshold[0][1]:
                    temp.append(2)
                elif i<self.threshold[0][2]:
                    temp.append(3)
                else:
                    temp.append(4)
        return np.asarray(temp)    
    
class categorise_10():
    def __init__(self):
        self.threshold=[]
        self.percentiles=[10,20,30,40,50,60,70,80,90]
        
    def fit(self,array):
        positive=array[array>0]
        negative=array[array<0]
        self.threshold.append(np.percentile(negative,self.percentiles))   
        self.threshold.append(np.percentile(positive,self.percentiles))
     
    def return_quartile(self,array):
        temp=[]
        for i in array:
            if i>=0:
                if i<self.threshold[1][0]:
                    temp.append(11)
                elif i<self.threshold[1][1]:
                    temp.append(12)
                elif i<self.threshold[1][2]:
                    temp.append(13)
                elif i<self.threshold[1][3]:
                    temp.append(14)
                elif i<self.threshold[1][4]:
                    temp.append(15)
                elif i<self.threshold[1][5]:
                    temp.append(16)
                elif i<self.threshold[1][6]:
                    temp.append(17)
                elif i<self.threshold[1][7]:
                    temp.append(18)
                elif i<self.threshold[1][8]:
                    temp.append(19)                    
                else:
                    temp.append(20)
            if i<0:
                if i<self.threshold[0][0]:
                    temp.append(1)
                elif i<self.threshold[0][1]:
                    temp.append(2)
                elif i<self.threshold[0][2]:
                    temp.append(3)
                elif i<self.threshold[0][3]:
                    temp.append(4)
                elif i<self.threshold[0][4]:
                    temp.append(5)
                elif i<self.threshold[0][5]:
                    temp.append(6)
                elif i<self.threshold[0][6]:
                    temp.append(7)
                elif i<self.threshold[0][7]:
                    temp.append(8)
                elif i<self.threshold[0][8]:
                    temp.append(9)                    
                else:
                    temp.append(10)
        return np.asarray(temp)    

In [45]:
def calc_smart_price(dataset):
    data=dataset[:]
    
    #to combat the limit up event, where price is set to 0. 
    rows=(data.loc[:,'BidPrice1']==0) #count rows of bid price equal 0
    if (np.any(rows)): #if there is such a row
        data.at[rows,'BidPrice1']=data.loc[rows,'AskPrice1'] #for that row, assign ask price to it
    rows=(data.loc[:,'AskPrice1']==0) #do the same for ask price
    if (np.any(rows)):
        data.at[rows,'AskPrice1']=data.loc[rows,'BidPrice1'] 
        
    data['smart_price']=data.loc[:,'BidPrice1']*data.loc[:,'AskVol1']+data.loc[:,'AskPrice1']*data.loc[:,'BidVol1']
    data.at[:,'smart_price']=data.loc[:,'smart_price']/(data.loc[:,['BidVol1','AskVol1']].sum(axis=1))  
    return data

def calc_present_vol(dataset):
    data=dataset[:]
    data['current_vol']=data.loc[:,'Volume'].diff().fillna(0)/2
    return data

def calc_future_price(dataset,time_ahead=30,time_index=44):
    data=dataset[:]
    future_price=[]
    length=len(data)
    for i in range(len(data)):
        current_time=data[i,time_index]+timedelta(seconds=time_ahead)
        #print(data[i,44])
        j=0
        #print(current_time)
        while((i+j)<length and current_time>data[(i+j),time_index]):
            j+=1
        if (i+j)<length:
            future_price.append(data[(i+j),-2]) #51 is the index for smart price            
        else:
            future_price.append(np.nan)
    future_price=np.asarray(future_price)
    future_price=np.expand_dims(future_price,axis=1)
    return np.concatenate((data,future_price),axis=1)


def calc_edge(dataset):
    data=dataset.copy()
    temp=data[:,-1]-data[:,-3]
    temp=np.expand_dims(temp,axis=1)
    return np.concatenate((data,temp),axis=1)

def set_index(dataset,time_index=44):
    data=dataset[:]
    index=data[:,time_index]
    new_index=[]
    for j in range(len(index)):
        i=str(index[j]*1000)
        if len(i)==11:
            i='0'+i
        i=i[:-10]+':'+i[-10:]
        i=i[:-8]+':'+i[-8:]
        i=i[:-6]+':'+i[-6:]
        new_index.append(datetime.strptime(i,"%H:%M:%S:%f"))
    data[:,time_index]=new_index
    return data

def calc_sma_fast(dataset,duration=1,time_index=44): #faster way to calculate SMA, 0.05 seconds for 5000 rows
    data=dataset[:]
    sma_values=[] 
    smart_sum=np.cumsum(data[:,-4]) #smart price column is -4
    for i in range(len(data)):
        last_time=data[i,time_index]-timedelta(minutes=duration)
        j=220*duration#4x60=240
        while(i-j>0 and data[i-j,time_index]>last_time):
            j+=1
        if (i-j>=0):
            sma=(smart_sum[i]-smart_sum[i-j])/(j)
            sma_values.append(sma)
        else:
            sma=smart_sum[i]/(i+1)
            sma_values.append(sma)

    sma_values=np.asarray(sma_values)
    sma_values=data[:,-4]-sma_values
    sma_values=np.expand_dims(sma_values,axis=1)
    return np.concatenate((data,sma_values),axis=1)  

def calc_past_vol(dataset,duration=1,time_index=44): #
    data=dataset[:].copy()
    vol_values=[] 
    vol_sum=np.cumsum(data[:,-4])
    for i in range(len(data)):
        last_time=data[i,time_index]-timedelta(minutes=duration)
        j=220*duration#4x60=240
        while(i-j>0 and data[i-j,time_index]>last_time):
            j+=1
        if (i-j>=0):
            vol=(vol_sum[i]-vol_sum[i-j])
            vol_values.append(vol)
        else:
            vol=vol_sum[i]
            vol_values.append(vol)
    vol_values=np.asarray(vol_values)
    vol_values=np.expand_dims(vol_values,axis=1)
    return np.concatenate((data,vol_values),axis=1) 

def process(dataset,sma_duration=1,vol_duration=1,time_index=44):
    data=dataset[:]
    data=calc_smart_price(data) #new
    data=calc_present_vol(data) #new 
    data=data.dropna()
    data=data.values 
    data=set_index(data,time_index=time_index) #no change
    data=calc_future_price(data,time_index=time_index) #new
    data=calc_edge(data) #new
    data=calc_sma_fast(data,duration=sma_duration,time_index=time_index) #new
    data=calc_past_vol(data,duration=vol_duration,time_index=time_index) #new
    return data

In [46]:
def process_files(path,file_list,sma_duration=1,time_index=44):
    df_list=[]
    name_list=[]
    print('processing files...')
    for file in file_list: #read all files and add them to file_list
        if file[-3:]=='csv': #check if file is a CSV
            name_list.append(file)
            df_list.append(process(pd.read_csv(path+file),sma_duration=sma_duration,time_index=time_index))   
            print(file)
    print('complete processing')
    return name_list,df_list

In [69]:
def run_analysis(df_path, df_list,name_list,sma_duration=1):
    error_list=[]
    final_df=pd.DataFrame()    

    for i in range(len(df_list)): #for each 20 day rolling window
        if i<19:
            continue
        if i==40:
            print('50% complete')
        
        
        #get -19 day
        sma=df_list[i-19][:,-2].copy() #column for SMA
        vol=df_list[i-19][:,-1].copy()

        #get -18 to 0 day (19 days in total)
        for k in range((i-18),i+1): #get 20 day moving averages
            sma=np.concatenate((sma,df_list[k][:,-2].copy()))
            vol=np.concatenate((vol,df_list[k][:,-1].copy()))

        cat_sma=categorise_10()
        cat_sma.fit(sma) #calculate quartile thresholds for past 20 days

        #get categories for past 20 days
        cat_sma_20=(cat_sma.return_quartile(sma))   

        #get x,y for regression
        x_today=df_list[i][:,-2].copy().astype(float) #column for SMA     
        y_today=df_list[i][:,-3].copy().astype(float) #column for edge

        vol_today=df_list[i][:,-1].copy()    
        #removing all NA
        isnum=(~np.isnan(x_today)) & (~np.isnan(y_today))
        #get categories of today's sma  
        cat_x_today=cat_sma.return_quartile(x_today)


        reg_result={}
        reg_result['date']=name_list[i]
        reg_result['total_obs']=len(x_today[isnum])   

        for cat in range(1,21):
            #check past 20 days quartiles and filter volume by category
            vol_fit=vol[cat_sma_20==cat].copy()

            #simple quartile categorisation
            cat_vol=categorise_simple()
            cat_vol.fit(vol_fit)


            #today's sma filter
            sma_filter_today=(cat_x_today==cat)
            #today's vol categories
            cat_vol_today=cat_vol.return_quartile(vol_today)


            for quartile in [1,2,3,4]:

                filtered= (isnum & sma_filter_today) #filtering NA and sma quartile
                filtered= filtered & (cat_vol_today==quartile) #filtering volume
                new_y=y_today[filtered].copy()

                q='ma_cat_'+str(cat)+'_vol_quartile'+str(quartile)+'_'
                if (len(new_y)!=0):

                    reg_result[(q+'mean')]=np.mean(new_y)
                    if np.abs(np.mean(new_y))>10:
                        error_list.append(new_y)
                        print('anomaly detected',i)
                    reg_result[(q+'std')]=np.std(new_y)
                    reg_result[(q+'num_obs')]=len(new_y)

                else:

                    reg_result[(q+'mean')]=np.nan
                    reg_result[(q+'std')]=np.nan
                    reg_result[(q+'num_obs')]='0'

        final_df=final_df.append(reg_result,ignore_index=True)                
    temp=df_path+'result_10sma,6vol_1min,'+str(sma_duration)+'min_sma,vol_mean.csv'
    final_df.to_csv(temp)
    print('done',temp)   
    return error_list

In [ ]:
for dir_path in dir_list:
    
    file_list=get_file_list(dir_path)
    file_list.sort()
    test_df=pd.read_csv(dir_path+file_list[1])
    
    test_columns=test_df.columns 
    time_index=np.where(test_columns=='Time')[0][0]         
    print('time index',time_index)
    
    for sma_duration in [3,5,10]:
        start=time.time()
        print('start',dir_path,sma_duration) 

        name_list,df_list=process_files(dir_path, file_list,sma_duration=sma_duration,time_index=time_index) #process, get SMA and vol data
        mid=time.time()
        print(mid-start)
        #split into categories and get means
        error_list=run_analysis(dir_path+'/results/', df_list,name_list,sma_duration=sma_duration)  
        if len(error_list)!=0:
            break
        end=time.time()
        print('complete',end-mid)

In [68]:
error_list

[array([ 8.4277482 ,  8.4153605 ,  8.67371353,  9.71717684,  9.85250664,
        24.12247971, 24.65314282, 24.46319072, 24.86883893, 24.66960762,
        23.49635926, 25.88133768, 25.25488249, 25.37282051]),
 array([25.23011217, 24.69408163, 24.03155726, 25.16373829, 24.94762684,
        25.1653578 , 25.03897334, 24.59804433, 21.01551957, 19.40295815,
        18.3875901 , 17.6774676 , 17.78872549, 17.9068126 , 16.71559252,
        16.60964539, 16.13476314])]

In [3]:
dir_path='/Users/hudsonyeo/Desktop/Python/leo/data/day'
dir_list_names=os.listdir(dir_path)
dir_list_names.sort()
dir_list=process_dir(dir_list_names)
#dir_list=dir_list[4:]
for i in range(len(dir_list)):
    dir_list[i]+='results/result_10sma,6vol_1min,'
dir_list,dir_list_names[1:]

(['/Users/hudsonyeo/Desktop/Python/leo/data/day/RM/results/result_10sma,6vol_1min,',
  '/Users/hudsonyeo/Desktop/Python/leo/data/day/SR/results/result_10sma,6vol_1min,',
  '/Users/hudsonyeo/Desktop/Python/leo/data/day/TA/results/result_10sma,6vol_1min,',
  '/Users/hudsonyeo/Desktop/Python/leo/data/day/c/results/result_10sma,6vol_1min,',
  '/Users/hudsonyeo/Desktop/Python/leo/data/day/fu/results/result_10sma,6vol_1min,',
  '/Users/hudsonyeo/Desktop/Python/leo/data/day/m/results/result_10sma,6vol_1min,',
  '/Users/hudsonyeo/Desktop/Python/leo/data/day/ni/results/result_10sma,6vol_1min,',
  '/Users/hudsonyeo/Desktop/Python/leo/data/day/zn/results/result_10sma,6vol_1min,'],
 ['RM', 'SR', 'TA', 'c', 'fu', 'm', 'ni', 'zn'])

In [ ]:
for i in dir_list_names[1:]:
    for num in [1,3,5,10]:
        path='/Users/hudsonyeo/Desktop/Python/leo/data/day/'+i+'/results/result_10sma,6vol_1min,'+str(num)+'min_sma,vol_mean.csv'
        print(i)
        print('sma:',num)
        data=pd.read_csv(path)
        x=[]
        x_std=[]
        pos=[]
        num_obs=[]
        for ma_cat in range(1,21):
            for vol_cat in range(1,5):
                col='ma_cat_'+str(ma_cat)+'_vol_quartile'+str(vol_cat)+'_mean'
                std=data.loc[:,col].std()
                mean=data.loc[:,col].mean()
                column=data.loc[:,col]
                x_std.append(std)
                x.append(mean)
                percentage=len(column[column>=0])/len(column)
                pos.append(percentage)  

                obs='ma_cat_'+str(ma_cat)+'_vol_quartile'+str(vol_cat)+'_num_obs'
                obs=data.loc[:,obs].sum()
                num_obs.append(obs)
        x=np.asarray(x)
        x=np.reshape(x,(20,4))
        x=np.around(x,3)
        x_std=np.asarray(x_std)
        x_std=np.reshape(x_std,(20,4))
        pos=np.asarray(pos)
        pos=np.reshape(pos,(20,4))
        num_obs=np.asarray(num_obs)
        num_obs=np.reshape(num_obs,(20,4))
        print('mean\n',x)
        print('std\n',x_std)
        print('% positive\n',pos)
        print('num obs\n',num_obs)

In [64]:
data=pd.read_csv('/Users/hudsonyeo/Desktop/Python/leo/data/day/fu/results/second/result_10sma,6vol_1min,5min_sma,vol_mean.csv')
x=[]
x_std=[]
pos=[]
num_obs=[]
for ma_cat in range(1,21):
    for vol_cat in range(1,5):
        col='ma_cat_'+str(ma_cat)+'_vol_quartile'+str(vol_cat)+'_mean'
        std=data.loc[:,col].std()
        mean=data.loc[:,col].mean()
        column=data.loc[:,col]
        x_std.append(std)
        x.append(mean)
        percentage=len(column[column>=0])/len(column)
        pos.append(percentage)  
        
        obs='ma_cat_'+str(ma_cat)+'_vol_quartile'+str(vol_cat)+'_num_obs'
        obs=data.loc[:,obs].sum()
        num_obs.append(obs)
x=np.asarray(x)
x=np.reshape(x,(20,4))
x=np.around(x,3)
x_std=np.asarray(x_std)
x_std=np.reshape(x_std,(20,4))
pos=np.asarray(pos)
pos=np.reshape(pos,(20,4))
num_obs=np.asarray(num_obs)
num_obs=np.reshape(num_obs,(20,4))
print('mean\n',x)
print('std\n',x_std)
print('% positive\n',pos)
print('num obs\n',num_obs)

mean
 [[ 0.194  0.183  0.285  0.565]
 [ 0.235  0.03  -0.014 -0.072]
 [ 0.103  0.057  0.004 -0.077]
 [ 0.029 -0.003 -0.047  0.091]
 [-0.068  0.03   0.095  0.012]
 [-0.017 -0.05  -0.058 -0.019]
 [-0.085  0.016 -0.073  0.021]
 [-0.029 -0.024 -0.009 -0.034]
 [ 0.001  0.073 -0.04  -0.021]
 [ 0.1    0.006 -0.02  -0.004]
 [ 0.24  -0.029  0.041  0.004]
 [ 0.151  0.08   0.008 -0.105]
 [ 0.024  0.087  0.046 -0.082]
 [ 0.08   0.023 -0.065 -0.166]
 [ 0.018  0.094  0.01  -0.024]
 [ 0.02  -0.014 -0.001 -0.004]
 [ 0.084  0.038 -0.105 -0.023]
 [-0.006  0.066 -0.001 -0.17 ]
 [ 0.125  0.058 -0.01   0.477]
 [-0.257  0.311  0.11  -0.564]]
std
 [[0.93956164 0.87898641 0.78070106 0.88553184]
 [0.51811005 0.47132081 0.66336174 0.8391233 ]
 [0.48218976 0.58471722 0.41383789 0.89423982]
 [0.41440251 0.46260968 0.42024159 0.7358212 ]
 [0.40166118 0.35035442 0.34101024 0.5733473 ]
 [0.37502983 0.42876114 0.44256151 0.58864317]
 [0.33205531 0.2972276  0.41919198 0.56233476]
 [0.31447083 0.42836695 0.38497326 0.53