In [1]:
import pandas as pd
import datetime
import numpy as np
from tqdm import tqdm_notebook
from datetime import datetime,timedelta
import os
from timeit import default_timer as timer
from scipy import stats
import matplotlib.pyplot as plt
dir_path='/Users/hudsonyeo/Desktop/Python/leo/data/day'
os.chdir('/Users/hudsonyeo/Desktop/Python/leo/data/day')
import time
def process_dir(dir_list):
    x=[]
    for dir_ in dir_list:
        if dir_!='.DS_Store':
            x.append(dir_path+'/'+dir_+'/')
    return x
standard_columns=pd.read_csv('/Users/hudsonyeo/Desktop/Python/leo/data/day/TA/2019.01.02.csv').columns

In [3]:
dir_list_names=os.listdir(dir_path)
dir_list_names.sort()
print(dir_list_names)
dir_list=process_dir(dir_list_names)
dir_list

['.DS_Store', 'RM', 'SR', 'TA', 'c', 'fu', 'm', 'ni', 'zn']


['/Users/hudsonyeo/Desktop/Python/leo/data/day/RM/',
 '/Users/hudsonyeo/Desktop/Python/leo/data/day/SR/',
 '/Users/hudsonyeo/Desktop/Python/leo/data/day/TA/',
 '/Users/hudsonyeo/Desktop/Python/leo/data/day/c/',
 '/Users/hudsonyeo/Desktop/Python/leo/data/day/fu/',
 '/Users/hudsonyeo/Desktop/Python/leo/data/day/m/',
 '/Users/hudsonyeo/Desktop/Python/leo/data/day/ni/',
 '/Users/hudsonyeo/Desktop/Python/leo/data/day/zn/']

In [6]:
get_file_list('/Users/hudsonyeo/Desktop/Python/leo/data/day/RM/')

['2019.04.23.csv',
 '2019.01.07.csv',
 '2019.04.22.csv',
 '2019.03.15.csv',
 '2019.04.08.csv',
 '2019.03.01.csv',
 '2019.03.29.csv',
 '2019.01.10.csv',
 '2019.01.04.csv',
 '2019.01.11.csv',
 '2019.03.28.csv',
 '2019.04.09.csv',
 '2019.03.14.csv',
 '2019.04.25.csv',
 '2019.04.19.csv',
 '2019.03.04.csv',
 '2019.01.29.csv',
 '2019.01.15.csv',
 '.DS_Store',
 '2019.01.14.csv',
 '2019.01.28.csv',
 '2019.03.05.csv',
 '2019.04.18.csv',
 '2019.03.11.csv',
 '2019.04.30.csv',
 '2019.04.24.csv',
 '2019.04.26.csv',
 '2019.03.07.csv',
 '2019.03.13.csv',
 '2019.01.02.csv',
 '2019.01.16.csv',
 '2019.01.17.csv',
 '2019.01.03.csv',
 '2019.03.12.csv',
 '2019.03.06.csv',
 '2019.02.21.csv',
 '2019.02.20.csv',
 '2019.02.22.csv',
 '2019.02.27.csv',
 '2019.05.06.csv',
 '2019.05.07.csv',
 '2019.02.26.csv',
 '2019.02.18.csv',
 '2019.02.19.csv',
 '2019.02.25.csv',
 '2019.02.28.csv',
 '2019.02.14.csv',
 '2019.05.09.csv',
 '2019.05.08.csv',
 '2019.02.01.csv',
 '2019.02.15.csv',
 'results',
 '2019.02.12.csv',
 '201

In [5]:
def get_file_list(dir_path):
    return os.listdir(dir_path)

class categorise():
    def __init__(self):
        self.threshold=[]
        self.percentiles=[25,50,75]
        
    def fit(self,array):
        positive=array[array>0]
        negative=array[array<0]
        self.threshold.append(np.percentile(negative,self.percentiles))   
        self.threshold.append(np.percentile(positive,self.percentiles))
     
    def return_quartile(self,array):
        temp=[]
        for i in array:
            if i>=0:
                if i<self.threshold[1][0]:
                    temp.append(5)
                elif i<self.threshold[1][1]:
                    temp.append(6)
                elif i<self.threshold[1][2]:
                    temp.append(7)
                else:
                    temp.append(8)
            if i<0:
                if i>self.threshold[0][2]:
                    temp.append(4)
                elif i>self.threshold[0][1]:
                    temp.append(3)
                elif i>self.threshold[0][0]:
                    temp.append(2)
                else:
                    temp.append(1)
        return np.asarray(temp)
    
class categorise_simple():
    def __init__(self):
        self.threshold=[]
        self.percentiles=[25,50,75]
        
    def fit(self,array):
        self.threshold.append(np.percentile(array,self.percentiles))
     
    def return_quartile(self,array):
        temp=[]
        for i in array:
                if i<self.threshold[0][0]:
                    temp.append(1)
                elif i<self.threshold[0][1]:
                    temp.append(2)
                elif i<self.threshold[0][2]:
                    temp.append(3)
                else:
                    temp.append(4)
        return np.asarray(temp)    
    
class categorise_10():
    def __init__(self):
        self.threshold=[]
        self.percentiles=[10,20,30,40,50,60,70,80,90]
        
    def fit(self,array):
        positive=array[array>0]
        negative=array[array<0]
        self.threshold.append(np.percentile(negative,self.percentiles))   
        self.threshold.append(np.percentile(positive,self.percentiles))
     
    def return_quartile(self,array):
        temp=[]
        for i in array:
            if i>=0:
                if i<self.threshold[1][0]:
                    temp.append(11)
                elif i<self.threshold[1][1]:
                    temp.append(12)
                elif i<self.threshold[1][2]:
                    temp.append(13)
                elif i<self.threshold[1][3]:
                    temp.append(14)
                elif i<self.threshold[1][4]:
                    temp.append(15)
                elif i<self.threshold[1][5]:
                    temp.append(16)
                elif i<self.threshold[1][6]:
                    temp.append(17)
                elif i<self.threshold[1][7]:
                    temp.append(18)
                elif i<self.threshold[1][8]:
                    temp.append(19)                    
                else:
                    temp.append(20)
            if i<0:
                if i<self.threshold[0][0]:
                    temp.append(1)
                elif i<self.threshold[0][1]:
                    temp.append(2)
                elif i<self.threshold[0][2]:
                    temp.append(3)
                elif i<self.threshold[0][3]:
                    temp.append(4)
                elif i<self.threshold[0][4]:
                    temp.append(5)
                elif i<self.threshold[0][5]:
                    temp.append(6)
                elif i<self.threshold[0][6]:
                    temp.append(7)
                elif i<self.threshold[0][7]:
                    temp.append(8)
                elif i<self.threshold[0][8]:
                    temp.append(9)                    
                else:
                    temp.append(10)
        return np.asarray(temp)    
    
class categorise_x(): #flexible number of categories
    
    def __init__(self,x):
        self.threshold=[]
        self.percentiles=[]
        self.num=x
        for i in range(1,x):
            self.percentiles.append(i*100/x)        
            
    def fit(self,array):
        
        positive=array[array>0]
        negative=array[array<=0]
        self.threshold.append(np.percentile(negative,self.percentiles))   
        self.threshold.append(np.percentile(positive,self.percentiles))
        
    def return_quartile(self,array):
        temp=[]
        for num in array:
            if num<0:
                counter=0
                for i in self.threshold[0]:
                    if num>=i:
                        counter+=1
                    else:
                        break
                temp.append(counter+1)
            else:
                counter=0
                for i in self.threshold[1]:
                    if num>=i:
                        counter+=1
                    else:
                        break
                temp.append(counter+self.num+1)
        return np.asarray(temp)
    
class cross():
    def __init__(self):
        self.time_last_cross=0
        self.current_sign=True
        self.last_time=datetime(1900, 1, 1, 8, 59)
    def get_time(self,time,price):
        if (time-self.last_time)>timedelta(minutes=1):
            self.last_time=time
            self.time_last_cross=time
            return 0
        self.last_time=time
        if (price>0) and self.current_sign : #if price positive and current trend is also positive
            return (time-self.time_last_cross).total_seconds()
        elif (price<0) and (not self.current_sign): #if price negative and current trend is negative
            return (time-self.time_last_cross).total_seconds()
        else: #if price positive, trend negative or price negative, trend positive
            self.time_last_cross=time
            self.current_sign=(price>0)
            return 0

In [8]:
def calc_smart_price(dataset):
    data=dataset.copy()
    
    #to combat the limit up event, where price is set to 0. 
    rows=(data.loc[:,'BidPrice1']==0) #count rows of bid price equal 0
    if (np.any(rows)): #if there is such a row
        data.at[rows,'BidPrice1']=data.loc[rows,'AskPrice1'] #for that row, assign ask price to it
    rows=(data.loc[:,'AskPrice1']==0) #do the same for ask price
    if (np.any(rows)):
        data.at[rows,'AskPrice1']=data.loc[rows,'BidPrice1'] 
        
    data['smart_price']=data.loc[:,'BidPrice1']*data.loc[:,'AskVol1']+data.loc[:,'AskPrice1']*data.loc[:,'BidVol1']
    data.at[:,'smart_price']=data.loc[:,'smart_price']/(data.loc[:,['BidVol1','AskVol1']].sum(axis=1))  
    return data

def calc_present_vol(dataset):
    data=dataset.copy()
    data['current_vol']=data.loc[:,'Volume'].diff().fillna(0)/2
    return data

def calc_future_price(dataset,time_ahead=30,time_index=44, price_col=-2):
    data=dataset.copy()
    future_price=[]
    length=len(data)
    for i in range(len(data)):
        current_time=data[i,time_index]+timedelta(seconds=time_ahead)
        
        j=0 #could alternatively use 30 x 3 then search forward and backward
        
        #search forwards
        while((i+j)<length and current_time>data[(i+j),time_index]):
            j+=1
        if (i+j)<length:
            #if index is in the dataframe
            future_price.append(data[(i+j),price_col]) 
        else:
            #price ahead does not exist
            future_price.append(np.nan) 
    future_price=np.asarray(future_price)
    future_price=np.expand_dims(future_price,axis=1)
    return np.concatenate((data,future_price),axis=1)

def calc_edge(dataset,future_col,current_col):
    data=dataset.copy()
    temp=data[:,future_col]-data[:,current_col]
    temp=np.expand_dims(temp,axis=1)
    return np.concatenate((data,temp),axis=1)

def set_index(dataset,time_index=44):
    data=dataset.copy()
    index=data[:,time_index].astype(int)
    new_index=[]
    for j in range(len(index)):
        i=str(index[j]*1000)
        if len(i)==11:
            i='0'+i
        i=i[:-10]+':'+i[-10:]
        i=i[:-8]+':'+i[-8:]
        i=i[:-6]+':'+i[-6:]
        new_index.append(datetime.strptime(i,"%H:%M:%S:%f"))
    data[:,time_index]=new_index
    return data

def calc_sma_fast(dataset,price_col,duration=1,time_index=44): #faster way to calculate SMA, 0.05 seconds for 5000 rows
    data=dataset.copy()
    sma_values=[] 
    smart_sum=np.cumsum(data[:,price_col]) #smart price column is -4
    for i in range(len(data)):
        
        #finding ending point
        last_time=data[i,time_index]-timedelta(minutes=duration)
        
        #finding start point
        j=220*duration#4x60=240
        
        if i-j>0:
            if data[i-j,time_index]>last_time: 
                
                #if starting point time is greater than ending point time
                #search backward
                while(i-j>0 and data[i-j,time_index]>last_time):
                    j+=1
                    
                #activate next line in order to debug and troubleshoot
                #if data[i-j,time_index]!=last_time:
                #    print('backward',i,j,data[i,time_index],data[i-j,time_index],last_time)

                sma=(smart_sum[i]-smart_sum[i-j])/j
                sma_values.append(sma)                
                
            else: 
                
                #search forward
                while(data[i-j,time_index]<last_time):
                    j-=1
                    
                #activate next line in order to debug and troubleshoot
                #if data[i-j,time_index]!=last_time:
                #    print('forward',i,j,data[i,time_index],data[i-j,time_index],last_time)
                
                if j!=0:
                    if data[i-j,time_index]!=last_time:
                        j+=1
                    sma=(smart_sum[i]-smart_sum[i-j])/j
                    sma_values.append(sma)   
                    
                else:
                    sma_values.append(data[i,price_col])
                    
        else: #starting point is at 0
            
            sma=smart_sum[i]/(i+1)
            sma_values.append(sma)                       

    sma_values=np.asarray(sma_values)
    sma_values=data[:,price_col]-sma_values
    sma_values=np.expand_dims(sma_values,axis=1)
    return np.concatenate((data,sma_values),axis=1)  

def calc_volatility_slow(dataset,price_col,duration=15,time_index=44): 
    data=dataset.copy()
    diff=np.diff(dataset[:,price_col])
    diff=np.insert(diff,0,0)
    
    volatility_values=[]
    for i in range(len(data)):
            
        #finding ending point
        last_time=data[i,time_index]-timedelta(minutes=duration)
        
        #finding start point
        j=220*duration#4x60=240
        
        if i-j>0:
            if data[i-j,time_index]>last_time: 
                #if starting point time is greater than ending point time
                #search backward
                while(i-j>0 and data[i-j,time_index]>last_time):
                    j+=1
                vol=np.std(diff[i-j:i])
                volatility_values.append(vol)                     
            else: 
                #search forward
                while(data[i-j,time_index]<last_time):
                    j-=1
                if j!=0:
                    vol=np.std(diff[i-j:i])
                    volatility_values.append(vol) 
                else:
                    volatility_values.append(0)
        else: #starting point is at 0
            if i==0:
                volatility_values.append(0)
                continue
            vol=np.std(diff[:i])
            volatility_values.append(vol)   
            
    volatility_values=np.asarray(volatility_values)
    volatility_values=np.expand_dims(volatility_values,axis=1)
    return np.concatenate((data,volatility_values),axis=1)

def calc_past_vol(dataset,vol_col,duration=1,time_index=44): #
    data=dataset.copy()
    vol_values=[] 
    vol_sum=np.cumsum(data[:,vol_col])
    for i in range(len(data)):
        last_time=data[i,time_index]-timedelta(minutes=duration)
        j=220*duration#4x60=240
        while(i-j>0 and data[i-j,time_index]>last_time):
            j+=1
        if (i-j>=0):
            vol=(vol_sum[i]-vol_sum[i-j])
            vol_values.append(vol)
        else:
            vol=vol_sum[i]
            vol_values.append(vol)
    vol_values=np.asarray(vol_values)
    vol_values=np.expand_dims(vol_values,axis=1)
    return np.concatenate((data,vol_values),axis=1) 

def last_cross(dataset,price_col,time_index=44):
    data=dataset.copy()
    last_cross=cross()
    timings=[]
    for i in range(len(data)):
        timings.append(last_cross.get_time(data[i,time_index],data[i,price_col]))
    timings=np.asarray(timings)
    timings=np.expand_dims(timings,axis=1)
    return np.concatenate((data,timings),axis=1)

def get_case(array):
    current=1
    previous=0
    temp=[]
    for i in array:
        if i==current:
            if i>previous:
                temp.append(1)
            else:
                temp.append(0)
        elif i>current:
            previous=current
            current=i
            temp.append(1)
        else:
            previous=current
            current=i
            temp.append(0)
    return np.asarray(temp)


def binaryToDecimal(binary): 
      
    binary1 = binary 
    decimal, i, n = 0, 0, 0
    while(binary != 0): 
        dec = binary % 10
        decimal = decimal + dec * pow(2, i) 
        binary = binary//10
        i += 1
    return(decimal) 
    
def get_case_n(array,n=2):
    temp=[]
    if n==1:
        return("error")
    previous=np.zeros(n+1)
    for i in array:
        #print(i,previous)
        final=''
        if i==int(previous[-1]):
            before=10
            for j in previous:
                if j>before:
                    final+='1'
                else:
                    final+='0'
                before=int(j)
            final=final[1:]
        else:
            before=10
            for j in previous[1:]:
                if j>before:
                    final+='1'
                else:
                    final+='0'
                before=int(j)
            final=final[1:]
            if i>before:
                final+='1'
            else:
                final+='0'
        
            previous=np.delete(previous,0)
            previous=np.insert(previous,n,i)
        #print(final)
        temp.append(binaryToDecimal(int(final)))
    return np.asarray(temp)    

def process(dataset,sma_duration=1,vol_duration=1,time_index=44):
    data=dataset.copy()
    data=calc_smart_price(data).values #new
    data=set_index(data,time_index=time_index) #no change
    data=calc_future_price(data,time_index=time_index,price_col=-1) #new
    data=calc_edge(data,future_col=-1,current_col=-2) #new
    data=calc_sma_fast(data,duration=sma_duration,time_index=time_index,price_col=-3) #new
    return data

def process_light(dataset,sma_duration=1,vol_duration=1):
    data=dataset.copy()
    data=calc_smart_price(data)
    data=data.loc[:,['Time','smart_price']].values.astype(object) #new
    data=set_index(data,time_index=0) #no change
    data=calc_future_price(data,time_index=0,price_col=-1) #new
    data=calc_edge(data,future_col=-1,current_col=-2) #new
    data=calc_sma_fast(data,duration=sma_duration,time_index=0,price_col=-3) #new
    return data

In [9]:
def process_files(path,file_list,sma_duration=1):
    df_list=[]
    name_list=[]
    print('processing files...')
    for file in file_list: #read all files and add them to file_list
        if file[-3:]=='csv': #check if file is a CSV
            name_list.append(file)
            df_list.append(process_light(pd.read_csv(path+file),sma_duration=sma_duration))
            print(file)
    print('complete processing')
    return name_list,df_list

In [14]:
def run_analysis(df_path, df_list,name_list,sma_duration,n=2):

    #create a list to hold all the data
    data_list=[]
    
    #creating a list for each category
    for i in range(20):
        data_list.append([])
        #creating a list for each quartile
        for _ in range((2**n)):
            data_list[i].append([])

    for i in range(len(df_list)): #for each 20 day rolling window
        if i<19: #skip first 19 days
            continue
        print(name_list[i])

        #get -19 day
        sma=df_list[i-19][:,-1].copy() #column for SMA

        #get -18 to 0 day (19 days in total)
        for k in range((i-18),i+1): #get 20 day moving averages
            sma=np.concatenate((sma,df_list[k][:,-1].copy()))

        cat_sma=categorise_10()
        cat_sma.fit(sma) #calculate quartile thresholds for past 20 days

        #get x,y for regression
        x_today=df_list[i][:,-1].copy().astype(float) #column for SMA     
        y_today=df_list[i][:,-2].copy().astype(float) #column for edge

        #removing all NA
        isnum=(~np.isnan(x_today)) & (~np.isnan(y_today))
        x_today=x_today[isnum]
        y_today=y_today[isnum]

        #get categories of today's sma  
        cat_x_today=cat_sma.return_quartile(x_today)

        change=get_case_n(cat_x_today.copy())

        #for each category
        for cat in range(1,21):

            #today's sma filter
            sma_filter_today=(cat_x_today==cat)

            #for each case
            for case in range(2**n):

                filtered= sma_filter_today & (change==case) #filtering by SMA and case
                filtered[:2]=False #removing first 2 entries due to insufficient data
                new_y=y_today[filtered].copy()

                if (len(new_y)!=0):
                    #add today's data into the list by category and case
                    data_list[(cat-1)][case].append(new_y) 

    final_df=pd.DataFrame()                 
    for cat in range(20):
        for case in range(2**n):
            reg_result={}
            if len(data_list[cat][case])==0:
                reg_result['category']=cat+1
                reg_result['case']=case+1
                reg_result['mean']=np.nan
                reg_result['std']=np.nan
                reg_result['num obs']=0
                final_df=final_df.append(reg_result,ignore_index=True)             
                continue

            #getting all the data needed to calculate mean and std
            all_data=data_list[cat][case][0].copy()
            for i in range(1,(len(data_list[cat][case]))):
                all_data=np.concatenate((all_data,data_list[cat][case][i].copy()))

            #adding results to output
            reg_result['category']=cat+1
            reg_result['case']=case+1
            reg_result['mean']=np.mean(all_data)
            reg_result['std']=np.std(all_data)
            reg_result['num obs']=len(all_data)
            final_df=final_df.append(reg_result,ignore_index=True) 

    temp=df_path+'result_10split_'+str(2**n)+'cases_'+str(sma_duration)+'min_sma_weightedmean.csv'
    final_df.to_csv(temp)
    print('done',temp)

In [ ]:
for dir_path in dir_list:
    
    file_list=get_file_list(dir_path)
    file_list.sort()
    
    for sma_duration in [1,3,5,10]:
        start=time.time()
        print('start',dir_path,sma_duration) 

        name_list,df_list=process_files(dir_path, file_list,sma_duration=sma_duration) #process, get SMA and vol data
        mid=time.time()
        print(mid-start)
        #split into categories and get means
        run_analysis(dir_path+'/results/', df_list,name_list,sma_duration=sma_duration)  
        
        end=time.time()
        print('complete',end-mid)

start /Users/hudsonyeo/Desktop/Python/leo/data/day/RM/ 1
processing files...
2019.01.02.csv
2019.01.03.csv
2019.01.04.csv
2019.01.07.csv
2019.01.08.csv
2019.01.09.csv
2019.01.10.csv
2019.01.11.csv
2019.01.14.csv
2019.01.15.csv
2019.01.16.csv
2019.01.17.csv
2019.01.18.csv
2019.01.21.csv
2019.01.22.csv
2019.01.23.csv
2019.01.24.csv
2019.01.25.csv
2019.01.28.csv
2019.01.29.csv
2019.01.30.csv
2019.01.31.csv
2019.02.01.csv
2019.02.11.csv
2019.02.12.csv
2019.02.13.csv
2019.02.14.csv
2019.02.15.csv
2019.02.18.csv
2019.02.19.csv
2019.02.20.csv
2019.02.21.csv
2019.02.22.csv
2019.02.25.csv
2019.02.26.csv
2019.02.27.csv
2019.02.28.csv
2019.03.01.csv
2019.03.04.csv
2019.03.05.csv
2019.03.06.csv
2019.03.07.csv
2019.03.08.csv
2019.03.11.csv
2019.03.12.csv
2019.03.13.csv
2019.03.14.csv
2019.03.15.csv
2019.03.18.csv
2019.03.19.csv
2019.03.20.csv
2019.03.21.csv
2019.03.22.csv
2019.03.25.csv
2019.03.26.csv
2019.03.27.csv
2019.03.28.csv
2019.03.29.csv
2019.04.01.csv
2019.04.02.csv
2019.04.03.csv
2019.04.

In [68]:
error_list

[array([ 8.4277482 ,  8.4153605 ,  8.67371353,  9.71717684,  9.85250664,
        24.12247971, 24.65314282, 24.46319072, 24.86883893, 24.66960762,
        23.49635926, 25.88133768, 25.25488249, 25.37282051]),
 array([25.23011217, 24.69408163, 24.03155726, 25.16373829, 24.94762684,
        25.1653578 , 25.03897334, 24.59804433, 21.01551957, 19.40295815,
        18.3875901 , 17.6774676 , 17.78872549, 17.9068126 , 16.71559252,
        16.60964539, 16.13476314])]

In [3]:
dir_path='/Users/hudsonyeo/Desktop/Python/leo/data/day'
dir_list_names=os.listdir(dir_path)
dir_list_names.sort()
dir_list=process_dir(dir_list_names)
#dir_list=dir_list[4:]
for i in range(len(dir_list)):
    dir_list[i]+='results/result_10sma,6vol_1min,'
dir_list,dir_list_names[1:]

(['/Users/hudsonyeo/Desktop/Python/leo/data/day/RM/results/result_10sma,6vol_1min,',
  '/Users/hudsonyeo/Desktop/Python/leo/data/day/SR/results/result_10sma,6vol_1min,',
  '/Users/hudsonyeo/Desktop/Python/leo/data/day/TA/results/result_10sma,6vol_1min,',
  '/Users/hudsonyeo/Desktop/Python/leo/data/day/c/results/result_10sma,6vol_1min,',
  '/Users/hudsonyeo/Desktop/Python/leo/data/day/fu/results/result_10sma,6vol_1min,',
  '/Users/hudsonyeo/Desktop/Python/leo/data/day/m/results/result_10sma,6vol_1min,',
  '/Users/hudsonyeo/Desktop/Python/leo/data/day/ni/results/result_10sma,6vol_1min,',
  '/Users/hudsonyeo/Desktop/Python/leo/data/day/zn/results/result_10sma,6vol_1min,'],
 ['RM', 'SR', 'TA', 'c', 'fu', 'm', 'ni', 'zn'])

In [ ]:
for i in dir_list_names[1:]:
    for num in [1,3,5,10]:
        path='/Users/hudsonyeo/Desktop/Python/leo/data/day/'+i+'/results/result_10sma,6vol_1min,'+str(num)+'min_sma,vol_mean.csv'
        print(i)
        print('sma:',num)
        data=pd.read_csv(path)
        x=[]
        x_std=[]
        pos=[]
        num_obs=[]
        for ma_cat in range(1,21):
            for vol_cat in range(1,5):
                col='ma_cat_'+str(ma_cat)+'_vol_quartile'+str(vol_cat)+'_mean'
                std=data.loc[:,col].std()
                mean=data.loc[:,col].mean()
                column=data.loc[:,col]
                x_std.append(std)
                x.append(mean)
                percentage=len(column[column>=0])/len(column)
                pos.append(percentage)  

                obs='ma_cat_'+str(ma_cat)+'_vol_quartile'+str(vol_cat)+'_num_obs'
                obs=data.loc[:,obs].sum()
                num_obs.append(obs)
        x=np.asarray(x)
        x=np.reshape(x,(20,4))
        x=np.around(x,3)
        x_std=np.asarray(x_std)
        x_std=np.reshape(x_std,(20,4))
        pos=np.asarray(pos)
        pos=np.reshape(pos,(20,4))
        num_obs=np.asarray(num_obs)
        num_obs=np.reshape(num_obs,(20,4))
        print('mean\n',x)
        print('std\n',x_std)
        print('% positive\n',pos)
        print('num obs\n',num_obs)

In [64]:
data=pd.read_csv('/Users/hudsonyeo/Desktop/Python/leo/data/day/fu/results/second/result_10sma,6vol_1min,5min_sma,vol_mean.csv')
x=[]
x_std=[]
pos=[]
num_obs=[]
for ma_cat in range(1,21):
    for vol_cat in range(1,5):
        col='ma_cat_'+str(ma_cat)+'_vol_quartile'+str(vol_cat)+'_mean'
        std=data.loc[:,col].std()
        mean=data.loc[:,col].mean()
        column=data.loc[:,col]
        x_std.append(std)
        x.append(mean)
        percentage=len(column[column>=0])/len(column)
        pos.append(percentage)  
        
        obs='ma_cat_'+str(ma_cat)+'_vol_quartile'+str(vol_cat)+'_num_obs'
        obs=data.loc[:,obs].sum()
        num_obs.append(obs)
x=np.asarray(x)
x=np.reshape(x,(20,4))
x=np.around(x,3)
x_std=np.asarray(x_std)
x_std=np.reshape(x_std,(20,4))
pos=np.asarray(pos)
pos=np.reshape(pos,(20,4))
num_obs=np.asarray(num_obs)
num_obs=np.reshape(num_obs,(20,4))
print('mean\n',x)
print('std\n',x_std)
print('% positive\n',pos)
print('num obs\n',num_obs)

mean
 [[ 0.194  0.183  0.285  0.565]
 [ 0.235  0.03  -0.014 -0.072]
 [ 0.103  0.057  0.004 -0.077]
 [ 0.029 -0.003 -0.047  0.091]
 [-0.068  0.03   0.095  0.012]
 [-0.017 -0.05  -0.058 -0.019]
 [-0.085  0.016 -0.073  0.021]
 [-0.029 -0.024 -0.009 -0.034]
 [ 0.001  0.073 -0.04  -0.021]
 [ 0.1    0.006 -0.02  -0.004]
 [ 0.24  -0.029  0.041  0.004]
 [ 0.151  0.08   0.008 -0.105]
 [ 0.024  0.087  0.046 -0.082]
 [ 0.08   0.023 -0.065 -0.166]
 [ 0.018  0.094  0.01  -0.024]
 [ 0.02  -0.014 -0.001 -0.004]
 [ 0.084  0.038 -0.105 -0.023]
 [-0.006  0.066 -0.001 -0.17 ]
 [ 0.125  0.058 -0.01   0.477]
 [-0.257  0.311  0.11  -0.564]]
std
 [[0.93956164 0.87898641 0.78070106 0.88553184]
 [0.51811005 0.47132081 0.66336174 0.8391233 ]
 [0.48218976 0.58471722 0.41383789 0.89423982]
 [0.41440251 0.46260968 0.42024159 0.7358212 ]
 [0.40166118 0.35035442 0.34101024 0.5733473 ]
 [0.37502983 0.42876114 0.44256151 0.58864317]
 [0.33205531 0.2972276  0.41919198 0.56233476]
 [0.31447083 0.42836695 0.38497326 0.53